name: ESLint

on:
  pull_request:
    types: ['opened','edited']
  pull_request_target:
    branches: '*'

jobs:        
  other:
      name: "different"
      if: github.repository == 'potatoooo'
      runs-on: ubuntu-latest
      steps:
        - name: sleep
          run: sleep 4
